#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error when substituting.
set -o pipefail # Return value of a pipeline is the value of the last command to exit with a non-zero status

# --- Script Usage ---
usage() {
    echo "Usage: $0 <json_list_file> <output_image_directory>"
    echo "  <json_list_file>: Path to the JSON file generated by 'nextflow inspect ... -format json'."
    echo "  <output_image_directory>: Directory where sanitized image .tgz files will be saved."
    exit 1
}

# --- Input Validation ---
if [ "$#" -ne 2 ]; then
    echo "Error: Incorrect number of arguments."
    usage
fi

JSON_LIST_FILE="$1"
OUTPUT_IMAGE_DIR="$2"

if [ ! -f "${JSON_LIST_FILE}" ]; then
    echo "Error: JSON list file not found: ${JSON_LIST_FILE}"
    exit 1
fi

# --- Dependency Check ---
command -v jq >/dev/null 2>&1 || { echo >&2 "Error: jq is required but not installed. Please install jq (e.g., 'sudo apt-get install jq' or 'sudo yum install jq'). Aborting."; exit 1; }
command -v docker >/dev/null 2>&1 || { echo >&2 "Error: Docker is required but not installed. Aborting."; exit 1; }

# --- Ensure output directory exists ---
echo ">>> Ensuring output directory exists: ${OUTPUT_IMAGE_DIR}"
mkdir -p "${OUTPUT_IMAGE_DIR}"

# --- Helper Function for Filename Sanitization ---
# Replaces '/' and ':' with '_'
sanitize_filename() {
    echo "$1" | tr '/:' '__'
}

# --- Process Images ---
echo ">>> Reading container URIs from: ${JSON_LIST_FILE}"
# Extract unique container URIs using jq
IMAGES=$(jq -r '.processes[].container | select(. != null and . != "")' "${JSON_LIST_FILE}" | sort -u)

if [ -z "${IMAGES}" ]; then
    echo "Warning: No container images found in ${JSON_LIST_FILE}."
    exit 0
fi

echo ">>> Found the following unique images:"
echo "${IMAGES}"
echo # Newline for spacing

IMAGES_PROCESSED=0
IMAGES_FAILED=0

echo ">>> Pulling and saving Docker images to ${OUTPUT_IMAGE_DIR}..."
for IMAGE in ${IMAGES}; do
    echo "--- Processing image: ${IMAGE} ---"
    IMAGES_PROCESSED=$((IMAGES_PROCESSED + 1))
    SANITIZED_NAME=$(sanitize_filename "${IMAGE}")
    OUTPUT_FILE="${OUTPUT_IMAGE_DIR}/${SANITIZED_NAME}.tgz" # Using .tgz extension as per example

    # Check if file already exists
    if [ -f "${OUTPUT_FILE}" ]; then
        echo "Skipping: Output file already exists: ${OUTPUT_FILE}"
        continue
    fi

    # Pull the image
    echo "Pulling ${IMAGE}..."
    if ! docker pull "${IMAGE}"; then
        echo "Error: Failed to pull image ${IMAGE}. Skipping." >&2
        IMAGES_FAILED=$((IMAGES_FAILED + 1))
        continue
    fi

    # Save the image
    echo "Saving image to ${OUTPUT_FILE}..."
    if ! docker save -o "${OUTPUT_FILE}" "${IMAGE}"; then
        echo "Error: Failed to save image ${IMAGE} to ${OUTPUT_FILE}. Skipping." >&2
        # Attempt to clean up potentially incomplete file
        rm -f "${OUTPUT_FILE}"
        IMAGES_FAILED=$((IMAGES_FAILED + 1))
        continue
    fi

    echo "--- Successfully processed and saved ${IMAGE} ---"
    echo # Newline for spacing
done

echo ">>> Finished processing images."
echo "Total unique images found: $(echo "${IMAGES}" | wc -l)"
echo "Images processed/saved in this run: $((IMAGES_PROCESSED - IMAGES_FAILED))"
echo "Images skipped (already existed): $(( $(echo "${IMAGES}" | wc -l) - IMAGES_PROCESSED ))"
echo "Images failed (pull or save): ${IMAGES_FAILED}"

if [ "${IMAGES_FAILED}" -gt 0 ]; then
    echo "Warning: ${IMAGES_FAILED} images failed to process."
    exit 1 # Exit with error if any image failed
else
    echo "✅ All required images processed successfully."
    exit 0
fi 