params {
    genome                       = null
    igenomes_ignore              = true
    custom_config_base           = null
    custom_config_version        = null
    pipelines_testdata_base_path = null
    modules_testdata_base_path   = null
    test_data_base               = null
    validate_params              = false
}
process.executor = 'local'
podman.enabled = true
podman.registry = null
